version: 2
updates:
#  - package-ecosystem: "uv"
#    directory: "/"
#    schedule:
#      interval: "weekly"
#      timezone: "Asia/Shanghai"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Shanghai"
