# Prometheus Alert Rules for GUI Agents Service
#
# Save this file as alert_rules.yml and reference it in prometheus.yml:
#   rule_files:
#     - "alert_rules.yml"

groups:
  - name: gui_agents_alerts
    interval: 30s
    rules:
      # Service Health Alerts
      
      - alert: ServiceDown
        expr: up{job="gui_agents"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "GUI Agents service is down"
          description: "The GUI Agents gRPC service has been down for more than 1 minute."
      
      - alert: HighTaskFailureRate
        expr: |
          (
            rate(agent_tasks_created_total{status="failed"}[5m]) /
            rate(agent_tasks_created_total[5m])
          ) > 0.2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High task failure rate detected"
          description: "More than 20% of tasks are failing (current: {{ $value | humanizePercentage }})."
      
      - alert: LowTaskSuccessRate
        expr: agent_task_success_rate < 0.7
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Low task success rate"
          description: "Task success rate is below 70% (current: {{ $value | humanizePercentage }})."
      
      # Resource Utilization Alerts
      
      - alert: HighTaskUtilization
        expr: agent_task_utilization > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High task utilization"
          description: "Task utilization is above 90% (current: {{ $value | humanizePercentage }}). Consider increasing max_concurrent_tasks."
      
      - alert: TaskUtilizationAtCapacity
        expr: agent_task_utilization >= 1.0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Task utilization at capacity"
          description: "All task slots are in use. New tasks will be rejected."
      
      - alert: HighMemoryUsage
        expr: agent_memory_usage_bytes > 2 * 1024 * 1024 * 1024  # 2GB
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Service memory usage is above 2GB (current: {{ $value | humanize1024 }}B)."
      
      # Performance Alerts
      
      - alert: HighTaskExecutionTime
        expr: |
          histogram_quantile(0.95,
            rate(agent_task_execution_duration_seconds_bucket[5m])
          ) > 300
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High task execution time"
          description: "95th percentile task execution time is above 5 minutes (current: {{ $value | humanizeDuration }})."
      
      - alert: HighTaskQueueWaitTime
        expr: |
          histogram_quantile(0.95,
            rate(agent_task_queue_wait_duration_seconds_bucket[5m])
          ) > 60
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High task queue wait time"
          description: "95th percentile queue wait time is above 1 minute (current: {{ $value | humanizeDuration }})."
      
      # gRPC Service Alerts
      
      - alert: HighGRPCErrorRate
        expr: |
          (
            rate(agent_grpc_errors_total[5m]) /
            rate(agent_grpc_requests_total[5m])
          ) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High gRPC error rate"
          description: "gRPC error rate is above 5% for method {{ $labels.method }} (current: {{ $value | humanizePercentage }})."
      
      - alert: HighGRPCLatency
        expr: |
          histogram_quantile(0.95,
            rate(agent_grpc_request_duration_seconds_bucket[5m])
          ) > 5
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High gRPC latency"
          description: "95th percentile gRPC latency is above 5 seconds for method {{ $labels.method }} (current: {{ $value | humanizeDuration }})."
      
      - alert: TooManyStreamConnections
        expr: sum(agent_grpc_stream_connections) > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Too many active stream connections"
          description: "Number of active stream connections is above 100 (current: {{ $value }})."
      
      # Cost and Resource Alerts
      
      - alert: HighTokenConsumptionRate
        expr: rate(agent_tokens_consumed_total{type="total"}[5m]) > 100000
        for: 10m
        labels:
          severity: info
        annotations:
          summary: "High token consumption rate"
          description: "Token consumption rate is above 100k tokens/5min (current: {{ $value | humanize }})."
      
      - alert: HighExecutionCost
        expr: rate(agent_execution_cost_total[1h]) > 10
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: "High execution cost"
          description: "Execution cost is above 10 {{ $labels.currency }}/hour (current: {{ $value }} {{ $labels.currency }}/hour)."
      
      # System Health Alerts
      
      - alert: TooManyTempFiles
        expr: agent_temp_files_count > 1000
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Too many temporary files"
          description: "Number of temporary files is above 1000 (current: {{ $value }}). Consider cleanup."
      
      - alert: StreamManagerOverload
        expr: agent_stream_manager_tasks > 50
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Stream manager overload"
          description: "Number of tasks in stream manager is above 50 (current: {{ $value }})."
