name: dependencies-guard.yml
on:
  workflow_dispatch:
#  push:
#    paths:
#      - 'uv.lock'

jobs:
  dep-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install uv
        run: make install-uv

      - name: Create virtual environment
        run: make create-venv

      - name: Build project for test
        run: make build
