name: Tag and Release

on:
  pull_request:
    types: [closed]

jobs:
  tag-and-release:
    if: |
     github.event.pull_request.merged == true &&
     startsWith(github.event.pull_request.title, 'build: bump Agentic-Lybic to')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      tag_name: ${{ steps.extract_tag.outputs.tag_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Extract tag name
        id: extract_tag
        run: |
          TAG_NAME=$(echo "${{ github.event.pull_request.title }}" | sed 's/build: bump Agentic-Lybic to //')
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Create and push tag
        run: |
          git tag ${{ steps.extract_tag.outputs.tag_name }}
          git push origin ${{ steps.extract_tag.outputs.tag_name }}

      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ steps.extract_tag.outputs.tag_name }} \
            --title "Release ${{ steps.extract_tag.outputs.tag_name }}" \
            --notes-file "CHANGELOGS/${{ steps.extract_tag.outputs.tag_name }}-release.md"

  publish-to-pypi:
    name: Publish Python Package to PyPI
    needs: tag-and-release
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/lybic
    permissions:
      id-token: write # Required for trusted publishing with OIDC

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        make install-uv
        make create-venv

    - name: Build package
      run: |
        source .venv/bin/activate
        make build

    - name: Publish package to PyPI
      env:
        UV_PUBLISH_USERNAME: __token__
        UV_PUBLISH_PASSWORD: ${{ secrets.LYBIC_PYPI_KEY }}
      run: make publish

  build-and-push-docker:
    name: Build and Push Docker Image
    needs: tag-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: lybic/lybic-guiagent
          tags: |
            type=raw,value=latest
            type=raw,value=${{ needs.tag-and-release.outputs.tag_name }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
